# 1단계: 빌드
FROM gradle:8.13-jdk17 AS builder
WORKDIR /app
COPY . .

RUN chmod +x gradlew && sed -i 's/\r$//' gradlew

RUN ./gradlew bootJar --no-daemon -x test

# 2단계: 실행
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java",\
            "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}",\
            "-jar",\
            "/app.jar"]