# Dockerfile-prod
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app

# (옵션) 헬스체크용 curl/wget 필요하면 하나만
RUN apk add --no-cache curl

# JAR 경로를 유연하게: 기본값=build/libs/*.jar
ARG JAR_FILE=build/libs/*SNAPSHOT.jar
COPY ${JAR_FILE} app.jar

EXPOSE 8080
ENTRYPOINT ["java","-Dspring.profiles.active=prod","-jar","/app/app.jar"]