## 1단계: 빌드
#FROM gradle:8.13-jdk17 AS builder
#WORKDIR /app
#COPY . .
#
#RUN chmod +x gradlew && sed -i 's/\r$//' gradlew
#
#RUN ./gradlew bootJar --no-daemon -x test
#
## 2단계: 실행
#FROM eclipse-temurin:17-jre-alpine
#WORKDIR /app
#COPY --from=builder /app/build/libs/*.jar app.jar
#ENTRYPOINT ["java",\
#            "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}",\
#            "-jar",\
#            "/app/app.jar"]

# ---- build
FROM gradle:8.13-jdk17 AS builder
WORKDIR /app
COPY gradlew gradlew
COPY gradle gradle
COPY settings.gradle build.gradle gradle.properties ./
RUN chmod +x gradlew && sed -i 's/\r$//' gradlew
RUN --mount=type=cache,target=/home/gradle/.gradle gradle dependencies --no-daemon || true
COPY . .
RUN --mount=type=cache,target=/home/gradle/.gradle gradle bootJar --no-daemon -x test

# ---- run
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
RUN apk add --no-cache curl
COPY --from=builder /app/build/libs/*.jar app.jar
ENTRYPOINT ["java",\
            "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE:-prod}",\
            "-jar",\
            "/app/app.jar"]
